SELECT ?item ?has_part ?has_partLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?item wdt:P31 wd:Q15099348.
  
  FILTER NOT EXISTS { ?item wdt:P527 ?has_part. }
  
}
