SELECT ?item ?metro_line WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?item wdt:P31 wd:Q15099348.
  
  FILTER NOT EXISTS { ?item wdt:P527 ?has_part. }
  
  ?metro_line wdt:P361 ?item.
  ?metro_line wdt:P31 wd:Q15079663.
}
